# Generated by Django 5.1.6 on 2025-07-05 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0003_loanpayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stafffile',
            name='staff',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
        migrations.DeleteModel(
            name='StaffFile',
        ),
    ]
