# Generated by Django 5.1.6 on 2025-07-08 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientapp", "0005_disbursement_repayment"),
    ]

    operations = [
        migrations.AddField(
            model_name="disbursement",
            name="account_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="disbursement",
            name="account_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="disbursement",
            name="bank_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
