# Generated by Django 5.1.6 on 2025-07-08 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientapp", "0006_disbursement_account_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="agreement_confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="loan",
            name="bvn",
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name="loan",
            name="employer_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="loan",
            name="gender",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="loan",
            name="guarantor_contact",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="loan",
            name="guarantor_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="loan",
            name="marital_status",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="loan",
            name="means_of_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="loan",
            name="membership_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
